
package pl.ug.jdbc;
import java.sql.*;


public class DBconn {
    DBconn(){}
    Connection c;
    PreparedStatement add;
    PreparedStatement update;
    PreparedStatement delete;
    Statement statement=null;
    public void createTableUsers() throws SQLException {
        statement= c.createStatement();

        String sql="CREATE TABLE IF NOT EXISTS USER (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY," +
                " username VARCHAR(25) NOT NULL, password VARCHAR(100) NOT NULL, " +
                "name VARCHAR(30) DEFAULT NULL)";
        statement.executeUpdate(sql);
        statement.close();
    }
    public void deleteTableUsers() throws SQLException {
        statement= c.createStatement();
        String sql="DROP TABLE IF EXISTS USER";
        statement.executeUpdate(sql);
        statement.close();
    }
    public void deleteUser(String name) throws SQLException {
        String sql="DELETE FROM USER WHERE username=?";
        delete=c.prepareStatement(sql);
        delete.setString(1, name);
        delete.executeUpdate();
        delete.close();

    }
    public void updateUser(String name, User u) throws SQLException {
        String sql="UPDATE USER SET username=?, password=?, name=? WHERE username=?";
        update = c.prepareStatement(sql);
        update.setString(1,u.getUsername());
        update.setString(2,u.getPassword());
        update.setString(3,u.getName());
        update.setString(4,name);
        int rowsUpdated = update.executeUpdate();
        if (rowsUpdated > 0) {
            System.out.println("An existing user was updated successfully!");
        }
        update.close();
    }
    public void selectAllUsers() throws SQLException {
        String sql="SELECT * FROM USER";
        statement= c.createStatement();

        ResultSet result = statement.executeQuery(sql);
        while(result.next()){
            System.out.println("ID: "+result.getString(1)+"\t USERNAME: "+ result.getString(2)+"\t PASSWD: " + result.getString(3)+ "\t NAME: "
                    +result.getString(4));
        }
        statement.close();
        result.close();
    }
    public void insertUser(User user) throws SQLException {
        add= c.prepareStatement("INSERT INTO USER(username,password,name) VALUES (?,?,?)");
        add.setString(1, user.getUsername());
        add.setString(2,user.getPassword());
        add.setString(3,user.getName());
        add.executeUpdate();
        add.close();
    }
    public void conn() throws SQLException {

            this.c=DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb", "SA", "");

    }

    public void dconn() throws SQLException {

        c.close();
    }

    public static void main(String[] args) throws SQLException {
       DBconn con= new DBconn();
       con.conn();
       //con.deleteTableUsers();
       con.createTableUsers();
       con.insertUser(new User("guest124", "qwerty", "Paweł"));
       con.insertUser(new User("haha","ewqfq","Jan"));
       con.selectAllUsers();
       con.deleteUser("guest124");
       con.updateUser("haha", new User("gg", "aa", "cc"));
       con.selectAllUsers();
       con.dconn();
    }
}

